### ISSUE TITLE
error after DB_PASSWORD  change

### ISSUE THREAD

**Issue by sez76** [pacoorozco/probind#269]
Hi,

I have change my DB_PASSWORD on .env and in phpAdmin, but when I connect is not working, I have the error below :
```SQLSTATE[HY000] [1045] Access denied for user 'laravel'@'172.18.0.4' (using password: YES) ```

Is there a further step ?

**Comment by pacoorozco** [comment]
So, once you have set up the same passwords in the DB and the .env file... **What's the problem?**

**Comment by sez76** [comment]
After I have change the .env & database password, I have this error message.
![image](https://user-images.githubusercontent.com/57563321/202385387-178fced1-e75e-449b-84a1-cfb9a6bc7d43.png)

**Comment by pacoorozco** [comment]
That message is thrown by Laravel, that's why I was suggesting to take a look to [their documentation](https://laravel.com/docs/9.x/installation#initial-configuration).

It means that the user 'laravel' (which will be the one you configured in the `.env` and DB) can't access to the DB in the '172.18.0.4' address (which should be the DB server). 

It could indicate that:
- Password is incorrect
- User doesn't not allow access from the app host

But none of them is related with the `gamify`-laravel application. In order to see it, you can test the app using the provided [Laravel Sail environment](https://github.com/pacoorozco/gamify-laravel#how-to-run-gamify).

**Comment by sez76** [comment]
Hi,

Alright, thank you for your feedback.

Sez
